config/routes.rb
Rails.application.routes.draw do
  
  
  resources :ordenproduccions do
    resources :materiales
  end

  resources :tallas

 
  devise_for :usuarios
 

  resources :cortes

  get 'welcome/index'
  get 'descripcioncortes/estadisticas'

  resources :colors

  resources :ordenproduccions do
    resources :descripcioncortes 
   
  end

    
    resources :descripcioncortes 

    resources :clientes

    resources :tallas
  
    resources :prendas
  
    resources :telas

    root 'welcome#index'

end

app/models/talla.rb
class Talla < ActiveRecord::Base
    has_many :instructores
end

app/controllers/tallas_controller.rb
class TallasController < ApplicationController
   before_action :authenticate_usuario!
  before_action :set_talla, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @tallas = Talla.all
    respond_with(@tallas)
  end

  def show
    respond_with(@talla)
  end

  def new
    @talla = Talla.new
    respond_with(@talla)
  end

  def edit
  end

  def create
    @talla = Talla.new(talla_params)
    @talla.save
    respond_with(@talla)
  end

  def update
    @talla.update(talla_params)
    respond_with(@talla)
  end

  def destroy
    @talla.destroy
    respond_with(@talla)
  end

  private
    def set_talla
      @talla = Talla.find(params[:id])
    end

    def talla_params
      params.require(:talla).permit(:nombre)
    end
end

app/helpers/tallas_helper.rb
module TallasHelper
end

app/views/tallas/_form.html.erb
<%= form_for(@talla) do |f| %>
  <% if @talla.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@talla.errors.count, "error") %> prohibited this talla from being saved:</h2>

      <ul>
      <% @talla.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tallas/edit.html.erb
<h1>Editing talla</h1>

<%= render 'form' %>

<%= link_to 'Show', @talla %> |
<%= link_to 'Back', tallas_path %>

app/views/tallas/index.html.erb
<div class="container">
  <h1>Listing tallas</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tallas.each do |talla| %>
      <tr>
        <td><%= talla.nombre %></td>
        <td><%= link_to 'Show', talla %></td>
        <td><%= link_to 'Edit', edit_talla_path(talla) %></td>
        <td><%= link_to 'Destroy', talla, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Talla', new_talla_path %>

</div>

app/views/tallas/new.html.erb
<h1>New talla</h1>

<%= render 'form' %>

<%= link_to 'Back', tallas_path %>

app/views/tallas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @talla.nombre %>
</p>

<%= link_to 'Edit', edit_talla_path(@talla) %> |
<%= link_to 'Back', tallas_path %>