config/routes.rb
Rails.application.routes.draw do
  
  
  resources :ordenproduccions do
    resources :materiales
  end

  resources :tallas

 
  devise_for :usuarios
 

  resources :cortes

  get 'welcome/index'
  get 'descripcioncortes/estadisticas'

  resources :colors

  resources :ordenproduccions do
    resources :descripcioncortes 
   
  end

    
    resources :descripcioncortes 

    resources :clientes

    resources :tallas
  
    resources :prendas
  
    resources :telas

    root 'welcome#index'

end

app/models/ordenproduccion.rb
class Ordenproduccion < ActiveRecord::Base
  

  
 
  belongs_to :cliente
  belongs_to :tela
  belongs_to :prenda
  belongs_to :corte
  has_many :descripcioncortes, dependent: :destroy
  has_many :materiales, dependent: :destroy


  def self.search(search, page)
      where(['upper(referencia) like ?',
      "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("referencia")
  end



   before_validation :sumas

    def sumas

      
   
    
    if largotrazo != nil && vecestrazo != nil         
      self.promedio = largotrazo / vecestrazo
      self.totalmetros = largotrazo * capas
    end  
    
      
  
    end



        

end

app/controllers/ordenproduccions_controller.rb
class OrdenproduccionsController < ApplicationController
  before_action :authenticate_usuario!
  before_action :set_ordenproduccion, only: [:show, :edit, :update, :destroy]
  # GET /ordenproduccions
  # GET /ordenproduccions.json
  def index
    @ordenproduccions = Ordenproduccion.search(params[:search], params[:page])
    @fondo_page = true
    @orden_p = true
    
    
  end

  # GET /ordenproduccions/1
  # GET /ordenproduccions/1.json
  def show    
     @home_pagee = true
     @footer_tuto1 = true

     @nocontainer = true
    
  end

  # GET /ordenproduccions/new
  def new
    @ordenproduccion = Ordenproduccion.new
    @fondo_aguja = true
    @footer_tuto = true
  end

  # GET /ordenproduccions/1/edit
  def edit
       
       @footer_tuto1 = true

  end

  # POST /ordenproduccions
  # POST /ordenproduccions.json
  def create
    @ordenproduccion = Ordenproduccion.new(ordenproduccion_params)
    
    if @ordenproduccion.largotrazo== nil then @ordenproduccion.largotrazo = 0 end
    if @ordenproduccion.vecestrazo== nil then @ordenproduccion.vecestrazo = 0 end
    if @ordenproduccion.capas== nil then @ordenproduccion.capas = 0  end
    
    respond_to do |format|
      if @ordenproduccion.save
        format.html { redirect_to @ordenproduccion, notice: 'Ordenproduccion was successfully created.' }
        format.json { render :show, status: :created, location: @ordenproduccion }
      else
        format.html { render :new }
        format.json { render json: @ordenproduccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ordenproduccions/1
  # PATCH/PUT /ordenproduccions/1.json
  def update
    if @ordenproduccion.largotrazo== nil then @ordenproduccion.largotrazo = 1 end
    if @ordenproduccion.vecestrazo== nil then @ordenproduccion.vecestrazo = 1 end
    if @ordenproduccion.capas== nil then @ordenproduccion.capas = 1 end
    
   
    respond_to do |format|
      if @ordenproduccion.update(ordenproduccion_params)
        format.html { redirect_to @ordenproduccion, notice: 'Ordenproduccion was successfully updated.' }
        format.json { render :show, status: :ok, location: @ordenproduccion }
      else
        format.html { render :edit }
        format.json { render json: @ordenproduccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ordenproduccions/1
  # DELETE /ordenproduccions/1.json
  def destroy
    @ordenproduccion.destroy
    respond_to do |format|
      format.html { redirect_to ordenproduccions_url, notice: 'Ordenproduccion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ordenproduccion
      @ordenproduccion = Ordenproduccion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ordenproduccion_params
      params.require(:ordenproduccion).permit(:fechaprogramacion, :cliente_id, :descripcion, :referencia, :corte_id, :ancho, :tela_id, :largotrazo, :largotendido, :promedio, :cantidad, :responsablecorte, :totalmetros, :tiqueteada, :prenda_id, :vecestrazo, :capas, :totalmetros, :descripcioncorte_id, :material_id)
    end
end

app/helpers/ordenproduccions_helper.rb
module OrdenproduccionsHelper
    
end

app/views/ordenproduccions/_form.html.erb
<%= form_for(@ordenproduccion) do |f| %>
  <% if @ordenproduccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ordenproduccion.errors.count, "error") %> prohibited this ordenproduccion from being saved:</h2>

      <ul>
      <% @ordenproduccion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="col-md-12 cubo ">
  <div class="col-md-4">
  
  <div class="field">
<h5><b>FECHA DE PROGRAMACIÓN</b></h5>
    <%= f.text_field :fechaprogramacion, class:'datepicker form-control' %>
  </div>
</div>
<div class="col-md-4">
   <div class="field">
    <h5><b>TIQUETEADA</b></h5>
    <%= f.text_field :tiqueteada, class:'form-control' %>
  </div>
 
</div>
<div class="col-md-4">
  
  
  <div class="field">
     
     <h5><b>CLIENTE</b></h5>
    <%= f.collection_select :cliente_id, Cliente.all, :id, :clientenombre,{prompt: "Seleccione Cliente"}, {class: "form-control"}  %>
  </div>
</div>



<br>
    <div class="col-md-4">
      <div class="field">
    <h5><b>REFERENCIA</b></h5>
    <%= f.text_field :referencia, class:'form-control' %>
  </div>
  </div>
<br>
  <div class="col-md-4">
      
  <div class="field">
     <h5><b>CORTE</b></h5>
    <%= f.collection_select :corte_id, Corte.all, :id, :cortenombre,{prompt: "Seleccione Corte"}, {class: "form-control"}  %>
  </div>
    <br> 
  </div>
 <br>
  <div class="col-md-4">
    <div class="field">
    <h5><b>ANCHO</b></h5>
    <%= f.text_field :ancho, class:'form-control' %>
  </div>
  </div>
<br>
</div>


<div class="col-md-12 cubo1">
   <div class="col-md-4">
     <div class="field">
     <h5><b>TELA</b></h5>
    <%= f.collection_select :tela_id, Tela.all, :id, :telanombre,{prompt: "Seleccione Tela"}, {class: "form-control"} %>
  </div>
  </div>
 
  <div class="col-md-4">
     <div class="field">
      <h5><b>LARGO DEL TRAZO</b></h5>
      <%= f.number_field :largotrazo , :type => 'float' , :in => 0..100, :step => 0.01, class:'form-control'%>
    </div>
  </div>
 
  <div class="col-md-4">
     <div class="field">
      <h5><b>VECES EN EL TRAZO</b></h5>
      <%= f.number_field :vecestrazo , :type => 'float' , :in => 0..100, :step => 0.01, class:'form-control'%>
    </div>
  </div>
<br>
    <div class="col-md-4">
   <div class="field">
    <h5><b>CAPAS</b></h5>
    <%= f.number_field :capas, class:'form-control' %>
  </div>
  </div>
 <br>
  <div class="col-md-4">
     <div class="field">
    <h5><b>CANTIDAD</b></h5>
    <%= f.text_field :cantidad, class:'form-control' %>
  </div>
  </div>
 <br>
  <div class="col-md-4">
      <div class="field">
    <h5><b>RESPONSABLE DEL CORTE</b></h5>
    <%= f.text_field :responsablecorte, class:'form-control' %>
  </div>
  </div>
  <br>
</div>
 

 <div class="col-md-12 cubo">
     <div class="col-md-4">
     <div class="field">
     <h5><b>PRENDA</b></h5>
    <%= f.collection_select :prenda_id, Prenda.all, :id, :prendanombre,{prompt: "Seleccione Prenda"},{ class: "form-control"} %>
  </div>

  </div>
 
  <div class="col-md-4">
    
    <div class="field">
    <h5><b>LARGO DEL TENDIDO</b></h5>
    <%= f.text_field :largotendido, class:'form-control', class:'form-control' %>
  </div>
    
  </div>
  
  <div class="col-md-4">
    
  </div>

    <br> <br>
  <div class="col-md-8">
  <div class="field">
    <h5><b>DESCRIPCIÓN</b></h5>
    <%= f.text_area :descripcion, class:'form-control' %>
  </div>
  </div>
  <br> <br>
  <div class="col-md-4">
       
       <div class="actions">
        <%= f.submit "GUARDAR",class:'btn btn-succes btn-lg btn-block questo tex1'%>
   <% end %>
  </div>
  </div>
  <br>
 
 </div> <br>

app/views/ordenproduccions/_formdescripcioncorte.html.erb
 
<div class="mode">

  
         

  <%= form_for([@ordenproduccion, @ordenproduccion.descripcioncortes.build]) do |f| %>


<h2 class=" center"> CORTE - <small>ORDEN #: <%= @ordenproduccion.id  %></small></h2> 
<div class="field">



  <div class="col-md-12">

   <h3 class="center"><b>Material</b></h3>
 <h2 class="zur1 center">Si <%= f.radio_button(:material, true) %>
 No <%= f.radio_button(:material, false) %></h2>
</div>

   <div class="col-md-3">
    <div class="field">
     
     
      <h5><b>COLOR</b></h5>
      <%= f.collection_select :color_id, Color.all, :id, :colornombre,{prompt: "Seleccione Color"},{ class: "form-control"} %>
    </div>
  </div>
  
  <div class="col-md-3">
   <div class="filed">
    
<button class="btn btn-succes tallaboton" role="button" data-toggle="collapse" href="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
<b>Tallas Letras</b>
</button>
   </div>
  </div>
  
   <div class="col-md-3">
   <div class="filed">
    
<button class="btn btn-succes tallaboton" role="button" data-toggle="collapse" href="#collapseExample2" aria-expanded="false" aria-controls="collapseExample">
<b>Tallas Unidad</b>
</button>
   </div>
  </div>


 <div class="col-md-3">
   <div class="filed">
    

<button class="btn btn-succes tallaboton " type="button" data-toggle="collapse" data-target="#collapseExample1" aria-expanded="false" aria-controls="collapseExample">
 <b>Tallas Unidades</b>
</button>
   </div>
  </div>


  
</div>





<div class="collapse" id="collapseExample">
  <div class="">

 <div class="col-md-12">
 <div class="col-md-1"></div>
 <div class="col-md-2"><div class="field">
     <h5><b>TALLA XS</b></h5>
     <%= f.number_field :tallaxs , class:'form-control', :id => 'xs', :onblur => 'sum()'%>
   </div></div>
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA S</b></h5>
   <%= f.number_field :tallas , class:'form-control', :id => 's', :onblur => 'sum()'%>
 </div></div>
 <div class="col-md-2"><div class="field">
     <h5><b>TALLA M</b></h5>
     <%= f.number_field :tallam , class:'form-control',:id => 'm', :onblur => 'sum()'%>
   </div></div>
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA L</b></h5>
   <%= f.number_field :tallal , class:'form-control', :id => 'l', :onblur => 'sum()'%>
 </div></div> 
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA XL</b></h5>
   <%= f.number_field :tallaxl , class:'form-control' , :id => "xl", :onblur => 'sum()' %>
 </div></div>
 <div class="col-md-1"></div>
</div>







  </div>
</div>
<div class="collapse" id="collapseExample2">
  <div class="col-md-12">
 <div class="col-md-1"></div>
 <div class="col-md-2"><div class="field">
     <h5><b>TALLA 6</b></h5>
     <%= f.number_field :talla6 , class:'form-control', :id => 'xs', :onblur => 'sum()'%>
   </div></div>
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA 8</b></h5>
   <%= f.number_field :talla8 , class:'form-control', :id => 's', :onblur => 'sum()'%>
 </div></div>
 <div class="col-md-2"><div class="field">
     <h5><b>TALLA 10</b></h5>
     <%= f.number_field :talla10 , class:'form-control',:id => 'm', :onblur => 'sum()'%>
   </div></div>
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA 12</b></h5>
   <%= f.number_field :talla12 , class:'form-control', :id => 'l', :onblur => 'sum()'%>
 </div></div> 
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA 14</b></h5>
   <%= f.number_field :talla14 , class:'form-control' , :id => "xl", :onblur => 'sum()' %>
 </div></div>
 <div class="col-md-1"></div>
</div>
</div>



<div class="collapse" id="collapseExample1">
  

<div class="col-md-12">
 <div class="col-md-1"></div>
 <div class="col-md-2"><div class="field">
     <h5><b>TALLA 28</b></h5>
     <%= f.number_field :talla28 , class:'form-control', :id => 'xs', :onblur => 'sum()'%>
   </div></div>
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA 30</b></h5>
   <%= f.number_field :talla30 , class:'form-control', :id => 's', :onblur => 'sum()'%>
 </div></div>
 <div class="col-md-2"><div class="field">
     <h5><b>TALLA 32</b></h5>
     <%= f.number_field :talla32 , class:'form-control',:id => 'm', :onblur => 'sum()'%>
   </div></div>
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA 34</b></h5>
   <%= f.number_field :talla34 , class:'form-control', :id => 'l', :onblur => 'sum()'%>
 </div></div> 
 <div class="col-md-2"><div class="field">
   <h5><b>TALLA 36</b></h5>
   <%= f.number_field :talla36 , class:'form-control' , :id => "xl", :onblur => 'sum()' %>
 </div></div>
 <div class="col-md-1"></div>
</div>

</div>




<div class="field invisi">

 <%= f.label :Tallasuma, class:''  %><br>
 <%= f.text_field :tallasuma , class:'form-control' , :id => "suma", :onblur => 'sum()' %>
</div>



<div class="col-md-12">
 <div class="col-md-8">

 </div> 
<br></br>
 <div class="col-md-4">
  <div class="actions">
    <%= f.submit "GUARDAR",class:'btn btn-succes questo tex2'%>
  </div>
</div>

</div>


<% end %>



</div>


 

app/views/ordenproduccions/edit.html.erb
<body class="aguja footer_tuto1">
    <h1 class="center"><b>EDICIÓN DE ORDEN</b></h1>
<br><br>

<div class="col-md-12">

<div class="col-md-1"></div>
<div class="col-md-10">
	
<%= render 'form' %>
</div>
<div class="col-md-1">
	<h4 class="center1">
	
<%= link_to "<i class='fa fa-eye fa-4x encima'></i>".html_safe, @ordenproduccion, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'left', :title => '', 'data-original-title' => 'Ver Orden' } %> 
<%= link_to "<i class='fa fa-arrow-circle-left fa-4x'></i>".html_safe, ordenproduccions_path, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Atras' } %>

</h4>
</div>
</div>



<br><br>
<div class="col-md-2">


</div>
</body>

app/views/ordenproduccions/index.html.erb
<body class="fonpage orden_p">
  <div class="col-md-12">

<div class="col-md-1"></div>
<div class="col-md-10">
  <h1 class="center"><b>ORDENES DE PRODUCCIÓN</b></h1> 
  <br>
<h4 class="derecho"><span class="badge option animated wobble" data-toggle="tooltip" data-placement="left" title="Cantidad de Ordenes"> <%= @ordenproduccions.count %> </span></h4 >

  <%= form_tag ordenproduccions_path, :method => 'get' do %>
  <% content_tag :label do %>

  <%= text_field_tag :search, params[:search], class:'form-control'  %> <br>
  <%= submit_tag "Buscar Referencia", :referencia => nil, class:'btn btn-succes  tex1'%>
  <% end %>
  <% end %>
 <br>

  <div class="table-responsive ">
    <div class="tbla">
      <table class="table table-condensed table-hover tbla">
        <thead>
          <tr class="active tablasom">
            <th><h3>Orden</h3></th>
            <th><h3>Referencia</h3></th>
            <th><h3>Fecha</h3></th>

            <th><h3>Descripcion</h3></th>

            <th><h3>Cantidad</h3></th>
          

            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% @ordenproduccions.each do |ordenproduccion| %>
          <tr>
            <td class="minus"><h3><b><%= ordenproduccion.id %></b></h3></td>
            <td class="minus"><h3><%= ordenproduccion.referencia %></h3></td>
            <td class="minus"><h5><%= ordenproduccion.fechaprogramacion %></h5></td>
            <td class="minus"><h4><%= ordenproduccion.descripcion %></h4></td>


            <td class="minus"><h3><%= ordenproduccion.cantidad rescue nil %></h3></td>
         

            <td><%= link_to "<i class='fa fa-eye fa-4x encima'>".html_safe, ordenproduccion, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Ver Orden' } %></td>
            <td><%= link_to "<i class='fa fa-pencil fa-4x encima'>".html_safe, edit_ordenproduccion_path(ordenproduccion), { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Editar Orden' } %></td>
            <td><%= link_to "<i class='fa fa-eraser fa-4x encima'>".html_safe, ordenproduccion, method: :delete, data: { confirm: 'Estas seguro?' } %></td>



          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <h3 class="center">
    
  <%= will_paginate @ordenproduccions, renderer: BootstrapPagination::Rails%> <br>
  </h3>

  <%= link_to "<i class='fa fa-plus-circle fa-4x'></i>".html_safe, new_ordenproduccion_path, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Agregar Orden' } %>

  <br>
</div>
<div class="col-md-1"></div>
  </div>

</body>

app/views/ordenproduccions/new.html.erb
<body class="agujaa footer_tuto">

        <h1 class="center"><b>NUEVA ORDEN</b></h1>
<br>

<div class="">
	<div class="col-md-12">
		
<div class="col-md-1"></div>
<div class="col-md-10">
	
<%= render 'form' %>
</div>
<div class="col-md-1"></div>

<h4 class="center">
	<%= link_to "<i class='fa fa-arrow-circle-left fa-4x'></i>".html_safe, ordenproduccions_path %>

</h4>

	</div>
</div>


</body>

app/views/ordenproduccions/show.html.erb
<body class="homepageesh footer_tuto1">


  <br>

  <div class="col-md-12">

    <div class="col-md-8">



      <div class="panel panel-succes">
        <div class="panel-heading center">
          <h3 class="panel-title">
          </h3>
          <h4><strong>Numero de Orden: </strong>
            <%= @ordenproduccion.id %> <br>
            <strong class="zur1">Centro de formación en diseño, confección y Moda</strong></h4>
          </div>
          <div class="panel-body">
            <div class="the-price">
             <div class="center-block">

              <%= image_tag("senab.png")%>
            </div>

          </div>
          <table class="table">
            <tr>
              <td>
                <div class="col-md-6">
                  <h5 class="izquierda1"> <strong >Fecha: </strong><%= @ordenproduccion.fechaprogramacion %></h5>

                </div>
                <div class="col-md-6">
                  <h5 class="derecha1"><strong>Cliente: </strong><%= @ordenproduccion.cliente.clientenombre rescue nil %></h5>

                </div>

              </td>
            </tr>


            <tr class="">
              <td>

               <div class="col-md-6">

                 <h5 class="izquierda1"> <strong>Referencia: </strong><%= @ordenproduccion.referencia %></h5>
               </div>
               <div class="col-md-6">
                 <h5 class="derecha1"><strong>Prenda: </strong>
                   <%= @ordenproduccion.prenda.prendanombre rescue nil %></h5>
                 </div>

               </td>
             </tr>
             <tr>
              <td>

                <div class="col-md-6">
                 <h5 class="izquierda1"><strong>Corte: </strong>
                   <%= @ordenproduccion.corte.cortenombre rescue nil %></h5>

                 </div>
                 <div class="col-md-6">
                   <h5 class="derecha1"> <strong>Ancho del Trazo: </strong>
                    <%= @ordenproduccion.ancho %></h5>

                  </div>




                </td>
              </tr>
              <tr class="">
                <td>
                  <div class="col-md-6">
                    <h5 class="izquierda1"> <strong>Tela: </strong>
                     <%= @ordenproduccion.tela.telanombre rescue nil %></h5>
                   </div>
                   <div class="col-md-6">
                     <h5 class="derecha1"> <strong>Largo del Trazo: </strong>
                      <%= @ordenproduccion.largotrazo.round(2) %></h5>


                    </div>





                  </td>
                </tr>
                <tr>
                  <td>

                    <div class="col-md-6">
                     <h5 class="izquierda1"> <strong>Veces en el Trazo: </strong>
                      <%= @ordenproduccion.vecestrazo.round(2) %> </h5>
                    </div>
                    <div class="col-md-6">
                     <h5 class="derecha1"> <strong>Largo del Tendido: </strong>
                      <%= @ordenproduccion.largotendido %>
                    </h5>
                  </div>



                </td>
              </tr>
              <tr class="">
                <td>

                  <div class="col-md-6">

                   <h5 class="izquierda1"> <strong>Promedio: </strong>
                    <%= @ordenproduccion.promedio.round(2) rescue nil %></h5>
                  </div>
                  <div class="col-md-6">
                    <h5 class="derecha1"> <strong>Cantidad: </strong>
                     <%= @ordenproduccion.cantidad %></h5>
                   </div>

                 </td>
               </tr>
               <tr>
                <td>

                  <div class="col-md-6">
                   <h5 class="izquierda1"> <strong>Responsable del Corte: </strong>
                     <%= @ordenproduccion.responsablecorte %>  </h5>
                   </div>
                   <div class="col-md-6">
                     <h5 class="derecha1"> <strong>Capas: </strong>
                      <%= @ordenproduccion.capas %></h5>
                    </div>


                  </td>
                </tr>

                <tr class="">
                  <td>

                    <div class="col-md-6">
                     <h5 class="izquierda1"> <strong>Total Metros:</strong>
                      <%= @ordenproduccion.totalmetros.round(2) %></h5>
                    </div>
                    <div class="col-md-6">
                      <h5 class="derecha1"><strong>Tiqueteada: </strong>
                        <%= @ordenproduccion.tiqueteada %></h5>

                      </div>


                    </td>
                  </tr>
                  <tr>
                    <td>
                     <div class="col-md-6"> <h5 class="izquierda1"><strong>Descripcion: </strong>
                      <%= @ordenproduccion.descripcion %></h5></div>

                    </td>
                  </tr>


                </table>
              </div>







              <div class="panel-footer">



                <strong class="zur1"><b>Centro de formación en diseño, confección y Moda</b></strong> <br>
                <%= link_to "<i class='fa fa-print fa-4x'></i>".html_safe, ordenproduccion_path(@ordenproduccion, :format => 'pdf'), { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'left', :title => '', 'data-original-title' => 'PDF' } %>   
                <%= link_to "<i class='fa fa-pencil fa-4x'></i>".html_safe, edit_ordenproduccion_path(@ordenproduccion) , { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'botton', :title => '', 'data-original-title' => 'Editar Orden de Producción' }%> 
                <%= link_to "<i class='fa fa-arrow-circle-left fa-4x'></i>".html_safe, ordenproduccions_path, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Atras' } %>


              </div>

     </div>




   </div>

   <div class="col-md-4">
     
<div class="fondocolor1">
    <br>
   
                <h2 class="center"><strong><b>Descripción del Corte</b></strong></h2>

 
<h4 class="center">
  <button class="btn" data-toggle="tooltip" data-placement="bottom" title="Click 'descripción de corte'">
    <i class="fa fa-bars fa-4x" type="button" data-toggle="collapse" data-target="#collapseshow" aria-expanded="false" aria-controls="collapseExample"></i>
</button>
</h4>
<br></br>

<div class="collapse" id="collapseshow">
 <h5 class="center">
   
 <i type="button" class="fa fa-plus-circle fa-4x" data-toggle="modal" data-target="#myModal">
 
</i>
 </h5>

 
     <%= render  "showdescripcion"%>
 
      
      
      <!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade bs-example-modal-lg" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="">
          <%= render  "formdescripcioncorte"%>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>
  </div>
  
  
  
  
</div>    
      <hr class="two"></hr>
      
      <div class="fondocolor2">
          <br>
                    <h2 class="center"><strong><b>Materiales</b></strong></h2>

          
      <h4 class="center">
        <button class="btn " data-toggle="tooltip" data-placement="bottom" title="Click 'Ver Materiales'">
        <i class="fa fa-caret-square-o-down fa-4x" type="button" data-toggle="collapse" data-target="#collapsematerial" aria-expanded="false" aria-controls="collapseExample">
         
        </i>
    </button>
      </h4>
    <br></br>
        <div class="collapse" id="collapsematerial">
          
          
        
        
          
      <h5 class="center">
              
            
 <i type="button" class="fa fa-plus-circle fa-4x" data-toggle="modal" data-target="#myModal1">
 
</i>

      </h5>
 
      <%= render  "showmateriales"%>
 
      
      
      <!-- Button trigger modal -->

<!-- Modal -->
<div class="modal fade bs-example-modal-lg" id="myModal1" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">

      <div class="">
            <%= render  "materialesform"%>
      </div>
      <div class="modal-footer">
        
      </div>
    </div>
  </div>
</div>
        
        
        </div>
      
      </div>
       </div>




   </div>
 </d  iv>

</body>





<a href="#" id="scrollup" data-toggle="tooltip" data-placement="top" title="Orden"></a>