config/routes.rb
Rails.application.routes.draw do
  
  
  resources :ordenproduccions do
    resources :materiales
  end

  resources :tallas

 
  devise_for :usuarios
 

  resources :cortes

  get 'welcome/index'
  get 'descripcioncortes/estadisticas'

  resources :colors

  resources :ordenproduccions do
    resources :descripcioncortes 
   
  end

    
    resources :descripcioncortes 

    resources :clientes

    resources :tallas
  
    resources :prendas
  
    resources :telas

    root 'welcome#index'

end

app/models/cliente.rb
class Cliente < ActiveRecord::Base
	
    validates :clientenombre, :presence =>true
    has_many :ordenproduccions
    
end

app/models/color.rb
class Color < ActiveRecord::Base
    
	has_many :descripcioncortes
	has_many :materiales
	
end

app/models/corte.rb
class Corte < ActiveRecord::Base
    has_many :ordenproduccions
end

app/models/descripcioncorte.rb
class Descripcioncorte < ActiveRecord::Base
  belongs_to :color
  belongs_to :ordenproduccion
 
  
  
   
  before_validation :sumatallas
  def sumatallas
    if tallal == nil || tallal < 0 then  
      self.tallal = 0
    end
    if tallam == nil || tallam < 0 then
      self.tallam = 0
    end
    if tallas == nil || tallas < 0 then
      self.tallas = 0
    end
    if tallaxl == nil || tallaxl < 0 then
      self.tallaxl = 0
    end
    if tallaxs == nil || tallaxs < 0 then
      self.tallaxs = 0
    end
    
    if talla6 == nil || talla6 < 0 then
      self.talla6 = 0
    end
    
    if talla8 == nil || talla8 < 0 then
      self.talla8 = 0
    end
    
    if talla10 == nil || talla10 < 0 then
      self.talla10 = 0
    end
    
    if talla12 == nil || talla12 < 0 then
      self.talla12 = 0
    end
    
    if talla14 == nil || talla14 < 0 then
      self.talla14 = 0
    end
    
    if talla28 == nil || talla28 < 0 then
      self.talla28 = 0
    end
    
    if talla30 == nil || talla30 < 0 then
      self.talla30 = 0
    end
    
    if talla32 == nil || talla32 < 0 then
      self.talla32 = 0
    end
    
    if talla34 == nil || talla34 < 0 then
      self.talla34 = 0
    end
    
    if talla36 == nil || talla36 < 0 then
      self.talla36 = 0
    end
    
    
      self.tallasuma = tallal + tallam + tallas + tallaxl + tallaxs + talla6 + talla8 + talla10 + talla12 + talla14 + talla28 + talla30 + talla32 + talla34 + talla36
  
  
      




  end

  
  
end

app/models/material.rb
class Material < ActiveRecord::Base
  belongs_to :tela
  belongs_to :color
  belongs_to :ordenproduccion
  
  
 
  
   before_validation :sumas
    
    def sumas
      
       if largotrazom == nil || largotrazom < 0 then  
          self.largotrazom = 0
      end
      if vecestrazom == nil || vecestrazom < 0 then  
          self.vecestrazom = 0
      end
      
      if capasm == nil || capasm < 0 then  
          self.capasm = 0
      end
  

      if largotrazom != nil && vecestrazom != nil         
        self.promedio = largotrazom / vecestrazom
        self.totalmetros = largotrazom * capasm
      end  
    
    end
  
  
  
end

app/models/ordenproduccion.rb
class Ordenproduccion < ActiveRecord::Base
  

  
 
  belongs_to :cliente
  belongs_to :tela
  belongs_to :prenda
  belongs_to :corte
  has_many :descripcioncortes, dependent: :destroy
  has_many :materiales, dependent: :destroy


  def self.search(search, page)
      where(['upper(referencia) like ?',
      "%#{search}%".upcase]).paginate(page: page, per_page: 5).order("referencia")
  end



   before_validation :sumas

    def sumas

      
   
    
    if largotrazo != nil && vecestrazo != nil         
      self.promedio = largotrazo / vecestrazo
      self.totalmetros = largotrazo * capas
    end  
    
      
  
    end



        

end

app/models/prenda.rb
class Prenda < ActiveRecord::Base
   validates :prendanombre, :presence =>true
   
   has_many :ordenproduccions 
   
end

app/models/talla.rb
class Talla < ActiveRecord::Base
    has_many :instructores
end

app/models/tela.rb
class Tela < ActiveRecord::Base
     validates :telanombre, :presence =>true
    
     has_many :ordenproduccions
     
     has_many :materiales
    
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
  
  
	
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/telas_controller.rb
class TelasController < ApplicationController
   before_action :authenticate_usuario!
  before_action :set_tela, only: [:show, :edit, :update, :destroy]
  # GET /telas
  # GET /telas.json
  def index
    @telas = Tela.all
  end

  # GET /telas/1
  # GET /telas/1.json
  def show
  end

  # GET /telas/new
  def new
    @tela = Tela.new
  end

  # GET /telas/1/edit
  def edit
  end

  # POST /telas
  # POST /telas.json
  def create
    @tela = Tela.new(tela_params)

    respond_to do |format|
      if @tela.save
        format.html { redirect_to @tela, notice: 'Tela was successfully created.' }
        format.json { render :show, status: :created, location: @tela }
      else
        format.html { render :new }
        format.json { render json: @tela.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /telas/1
  # PATCH/PUT /telas/1.json
  def update
    respond_to do |format|
      if @tela.update(tela_params)
        format.html { redirect_to @tela, notice: 'Tela was successfully updated.' }
        format.json { render :show, status: :ok, location: @tela }
      else
        format.html { render :edit }
        format.json { render json: @tela.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /telas/1
  # DELETE /telas/1.json
  def destroy
    @tela.destroy
    respond_to do |format|
      format.html { redirect_to telas_url, notice: 'Tela was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tela
      @tela = Tela.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tela_params
      params.require(:tela).permit(:telanombre)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clientes_helper.rb
module ClientesHelper
end

app/helpers/colors_helper.rb
module ColorsHelper
end

app/helpers/cortes_helper.rb
module CortesHelper
end

app/helpers/materiales_helper.rb
module MaterialesHelper
end

app/helpers/prendas_helper.rb
module PrendasHelper
end

app/helpers/tallas_helper.rb
module TallasHelper
end

app/helpers/telas_helper.rb
module TelasHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div id="button"></div>
	<div id="container">
		<div id="cont">
			<div class="footer_center">
	   
		  
		   <h3 class=" letrablanca ">
		   	
		   	<%if @orden_p == true %>
				<body class="orden_p">
				<h2>
					<i><%= link_to "COLORES", colors_path%></i>
					<i><%= link_to "TELAS", telas_path%></i>
					<i><%= link_to "PRENDAS", prendas_path%></i>
					<i><%= link_to "CLIENTES", clientes_path%></i>
					<i><%= link_to "TALLAS", tallas_path%></i>
					<i><%= link_to "CORTES", cortes_path%></i>
					</h2>
					
				
				</body>
			
			<%elsif @footer_tuto == true%>
				<body class="footer_tuto">
					 Soporte Técnico: <br>
					 	<i class='fa fa-user-md fa-2x'><br>jahenao17@misena.edu.co</i>  
				   		
			    </body>
			<%elsif @footer_tuto1 == true%>
				<body class="footer_tuto1">
					<h2>CENTRO DE FORMACIÓN EN DISEÑO, CONFECCIÓN Y MODA</h2>
				</body>
		   
		   <%elsif @fondo_desc == true%>
		   <body class="fondo_desc">
		   			<h2><i><%= link_to "COLORES", colors_path%></i>
					<i><%= link_to "TELAS", telas_path%></i>
					<i><%= link_to "PRENDAS", prendas_path%></i>
					<i><%= link_to "CLIENTES", clientes_path%></i>
					<i><%= link_to "TALLAS", tallas_path%></i>
					<i><%= link_to "CORTES", cortes_path%></i></h2>
					
		   </body>
		   
		   <%elsif @footer_terce == true%>
		   <body class="footer_terce">
		   	 		
					<i class='fa fa-eye  '>  Mostrar la Orden</i><br>
					<i class='fa fa-pencil  '>  Editar la Orden</i><br>
					<i class='fa fa-plus-circle fa-2x '> Crear nueva Orden</i>
		   </body>
		   
		   <%elsif @footer_welcome == true%>
		   <body class="footer_welcome">
		   	
		   <% if usuario_signed_in? %>	
		   
		   <h2>CENTRO DE FORMACIÓN EN DISEÑO, CONFECCIÓN Y MODA</h2>
		   <% elsif%>
		   <br>
		   <a href="https://www.youtube.com/embed/Rv6ft2W6W1Q"><i class="fa fa-youtube-play fa-4x"></i></a>
		   <%end%>	
		   
		   </body>
		   
		   
		   <% elsif @tuto_video == true%>
		   
		   <body class="tuto">
		   	<i class='fa fa-eye fa-2x'> Ingresar a Instructor </i> <br>
		   	<a href="https://www.youtube.com/watch?v=HL8GiGhU3ac"><i class="fa fa-youtube-play fa-2x"></i></a>
		   </body>
		   
		   <% elsif @tuto_videoins == true%>
		   <body class="tutovi">
		   	<i class='fa fa-user-md fa-2x'><br>jahenao17@misena.edu.co</i> <br>
		   	<a href="https://www.youtube.com/embed/W_1Nc-pQ-gs"><i class="fa fa-youtube-play fa-2x"></i></a> 
		   </body>
		   
		   <% elsif @tuto_estadisticas == true%>
		   <body class="estadisticas">
		   <i><%= link_to "COLORES", colors_path%></i>
					<i><%= link_to "TELAS", telas_path%></i>
					<i><%= link_to "PRENDAS", prendas_path%></i>
					<i><%= link_to "CLIENTES", clientes_path%></i>
					<i><%= link_to "TALLAS", tallas_path%></i>
					<i><%= link_to "CORTES", cortes_path%></i>
					
		   	
		   	
		   	 
		   </body>
		   
		   
		   
		   
			<%end%>
			
			
			</h3>
	   
</div>
</div>
</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>ControlProduccion</title>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	<%= csrf_meta_tags %>
</head>

<% if @home_pagee == true %>
<body class="homepage">
	<% elsif @home_page == true %>
	<body class="homepage">
		<% elsif @fondo_page == true %>
		<body class="fonpage">
			<% elsif @fondo_hand == true %>
			<body class="handfondo">
				<% elsif @fondo_cuadro == true %>
				<body class="fondo_cuadro">
					<% elsif 	@home_pagee12 == true %>
				<body class="homepageesh12">
				


					<% end %>


<% if @nocontainer == true || @fondo_page == true %>

							<% if usuario_signed_in? %>
							<nav class="navbar navbar-fixed-left navbar-minimal animate" role="navigation">
								<div class="navbar-toggler animate">
									<span class="menu-icon"></span>
								</div>
								<ul class="navbar-menu animate">


									


									<li><%= link_to "<i class='fa fa-code fa-2x too questo'></i>".html_safe,  ordenproduccions_path,  { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Ordenes de Producción' }  %></li>
									
									
									<%# if current_usuario == Usuario.find(1)%>
									
										<li><%= link_to "<i class='fa fa-bar-chart fa-2x questo'></i>".html_safe, descripcioncortes_estadisticas_path, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Estadisticas' }  %></li>
										
										
										
									<%# end%>
									
									<li><%= link_to "<i class='fa fa-user-times fa-2x questo'></i>".html_safe, destroy_usuario_session_path, :method => :delete, class: 'active' %></li>


								</ul>
							</nav>
				
			
							<% end%>


							<div class="container">
								<span class="label label-default animated shake "><%= notice %></span>
							<span class="label label-default animated shake"><%= alert %></span>
							</div>
							
						
				
							<%= yield %>
<% elsif %>


<div class="">
	<div class="">
		<% if usuario_signed_in? %>
							<nav class="navbar navbar-fixed-left navbar-minimal animate" role="navigation">
								<div class="navbar-toggler animate">
									<span class="menu-icon"></span>
								</div>
								<ul class="navbar-menu animate">


									


									<li><%= link_to "<i class='fa fa-code fa-2x too questo'></i>".html_safe,  ordenproduccions_path,  { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Ordenes de Producción' }  %></li>
									
									
									<%# if current_usuario == Usuario.find(1)%>
									
										<li><%= link_to "<i class='fa fa-bar-chart fa-2x questo'></i>".html_safe, descripcioncortes_estadisticas_path, { :class => 'tooltips', 'data-toggle' => 'tooltip', 'data-placement' => 'right', :title => '', 'data-original-title' => 'Estadisticas' }  %></li>
										
										
										
									<%# end%>
									
									<li><%= link_to "<i class='fa fa-user-times fa-2x questo'></i>".html_safe, destroy_usuario_session_path, :method => :delete, class: 'active' %></li>


								</ul>
							</nav>
				
			
							<% end%>

<div class="container">
	
							<span class="label label-default animated shake "><%= notice %></span>
							<span class="label label-default animated shake"><%= alert %></span>
							
</div>
						
				
							<%= yield %>
	</div>
</div>


<% end%>




					<br><br>


					<%= render 'layouts/footer' %>

</body>
</html>


</body>
</html>